name: 'Build demo-ms-one application'

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Container Image Tag'
        required: true
        default: 'latest'
      shouldPushImageToDockerHub:
        description: 'Push Container Image To DockerHub'
        type: boolean


jobs: 
  build-container-image:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # Default is dockerHub
          # registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./demo-ms-one/Dockerfile
          push: ${{ github.event.inputs.shouldPushImageToDockerHub }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/logging-tracing.demo-ms-one:${{ github.event.inputs.imageTag }}
        

